#pragma once

#include "resource.h"


enum class CONNECTION_STATUS : UINT8 { STOPPED, STOPPING, LISTENING, CONNECTED };
enum class FILE_TRANSFER_STATUS : UINT8 { STOPPED, ACTIVE };


#ifndef FORMATED_TIME_STAMP_SIZE
#define FORMATED_TIME_STAMP_SIZE (0x20)
#endif



VOID changeIcon(CONNECTION_STATUS state);

VOID toggleFileBtn(FILE_TRANSFER_STATUS state);
